<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>d0918285-05af-44e6-875d-64867f3ab5e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>area[alt=&quot;Birds&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/map/area</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Birds&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>59626e16-bc91-4510-be9f-7f0515a8c0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Birds</value>
      <webElementGuid>c29044ce-2d8a-4802-8ed3-8c883955a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>72,2,280,250</value>
      <webElementGuid>53ceaf9d-6c39-4e3a-8896-b547b255243b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Catalog.action?viewCategory=&amp;categoryId=BIRDS</value>
      <webElementGuid>eea91b7f-f8c0-4bf5-996a-0b65ac3de184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>RECT</value>
      <webElementGuid>ce4a0b2f-a37e-4b7c-baaa-babc5ef09abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/map[1]/area[1]</value>
      <webElementGuid>861276d5-4abd-4897-90be-a5d82168c3c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/map/area</value>
      <webElementGuid>e74f1515-4faf-4978-aace-1b24b918ce42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area</value>
      <webElementGuid>c6648180-c4f3-4dde-8145-4ed518ad959f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@alt = 'Birds' and @href = 'Catalog.action?viewCategory=&amp;categoryId=BIRDS']</value>
      <webElementGuid>a7a35861-4c00-41d0-afc6-904e7b3b8528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
